config/routes.rb
TravelApp::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to => "welcome#index"

  resources :companionships
  resources :friendships
  resources :favorites
  resources :iteneraries
  resources :cities
  resources :trips
  resources :users

  resources :comments, :only => [:create, :destroy]

  get 'tags/:tag', to: 'trips#index', as: :tag

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :begin_on, :end_on, :like, :title, :user_id, :cities_attributes, :body, :tag_list
  belongs_to :user, inverse_of: :trips
  has_many :cities, inverse_of: :trip
  accepts_nested_attributes_for :cities, allow_destroy: true, reject_if: :all_blank
  acts_as_commentable
  acts_as_taggable
  has_many :comments, as: :commentable

  validates_presence_of :begin_on, :end_on, :title, :user_id
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :authenticate_user!#, except: [:index, :show]
  # GET /trips
  # GET /trips.json
  def index
    @trips = current_user.trips.all
    if params[:tag]
      @trips = current_user.trips.tagged_with(params[:tag])
    else
      @trips = current_user.trips.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  def create_comment
    @trip = Trip.find(params[:id])
    @comment = @trip.comments.new params[:comment]
    redirect_to :action => :show, :id => trip

    # @post = @post.find params[:post_id]
    # @comment = @post.comments.new params[:comment]
    # if @comment.save
    # redirect_to @post

    # @trip = Trip.find(params[:id])
    # @user_who_commented = @current_user
    # @comment = Comment.build_from( @trip, @user_who_commented.id, "Hey guys this is my comment!" )
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @trip, notice: 'Comment was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_comment
    @trip = Trip.find(params[:id])
    @comments = @trip.comments.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])
    @comments = @trip.comment_threads.order('created_at desc')
    @new_comment = Comment.build_from(@trip, current_user, "")
    # @user_who_commented = current_user
    # @commentable = @trip
    # @comments = @commentable.comments
    # @comment = Comment.new#(:body => params[:body], :user_id => @user_who_commented)

    # @cities_in_current_trip = City.joins(:trip).where(cities: {trip_id: @trip.id})
    # @iteneraries_of_current_trip = Itenerary.joins(:city).where(iteneraries: {trip_id: @trip.id})


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new
    @trip.cities.build
    @trip.cities.each do |t|
      t.iteneraries.build
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])
    @trip.user_id = current_user.id

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_city_fields.html.erb
<li class="city">
<div class="row">
    <div class="small-2 large-6 columns">
      <%= f.label :name, "City" %>
      <%= f.text_field :name %>
    </div>
    <div class="small-2 large-6 columns">
      <%= f.label :country %>
      <%= f.text_field :country %>
    <div>

</div>
<h3 class="title-box">Trip / City / Itenerary</h3>

      <div class="nested-level-2">
        <ul class="iteneraries-container">
          <%= f.nested_fields_for :iteneraries, new_item_index: 'new_itenerary_item', html: { class: "itenerary-form" } do |f| %>
          <div class="row">
            <li class="itenerary">
              <div class="small-2 large-3 columns">
                <%= f.label :item %>
                <%= f.text_field :item %>
              </div>
              <div class="small-2 large-3 columns">
                <%= f.check_box :activity_to_do %>
                <%= f.label :activity_to_do %>
              </div>
              <div class="small-2 large-3 columns">
                <%= f.check_box :place_to_eat %>
                <%= f.label :place_to_eat %>
              </div>
              <div class="small-2 large-3 columns">
                <%= f.check_box :place_to_sleep %>
                <%= f.label :place_to_sleep %>
              </div>

              <a href="#" class="itenerary-remove">remove</a>

              <%= f.hidden_field :id %>
              <%= f.hidden_field :_destroy %>
              <hr />
            </li>
          </div>
          <% end %>
        </ul>
        <a href="#" class="itenerary-add">Add Itenerary</a>
    </div>
  <a href="#" class="itenerary-remove">remove</a>
  <%= f.hidden_field :id %>
  <%= f.hidden_field :_destroy %>
</li>

app/views/trips/_city_list.html.erb
<h1>Listing cities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>Trip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.name %></td>
    <td><%= city.country %></td>
    <td><%= city.trip_id %></td>
    <td><%= link_to 'Show', city %></td>
    <td><%= link_to 'Edit', edit_city_path(city) %></td>
    <td><%= link_to 'X', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New City', new_city_path %>
g

app/views/trips/_form.html.erb
<div class="light-box">
<%= form_for @trip, :html => { :class => "trip-form" } do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="row">
      <div class="small-2 large-3 columns">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="small-2 large-3 columns">
        <%= f.label :begin_on %>
        <%= f.text_field :begin_on %>
      </div>
      <div class="small-2 large-3 columns">
        <%= f.label :end_on %>
        <%= f.text_field :end_on %>
      </div>
      <div class="small-2 large-3 columns">
        <%= f.label :open, "Is this trip open to other travelers?" %>
        <%= f.check_box :open %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 large-12 columns">
        <%= f.label :tag_list, "Tags (separated by commas)" %>
        <%= f.text_field :tag_list %>
      </div>
    </div>
      <h2 class="title-box-light">
        Trip / Cities
        <%= f.submit :class => "tiny button right" %>
      </h2>
      <ul class="cities-container">
        <%= f.nested_fields_for :cities, render_template: false, new_item_index: 'new_city_item' do |f| %>
          <div class="iten-box"><%= render 'city_fields', f: f %></div>
        <% end %>
      </ul>
    <%= nested_fields_templates %>
    <a href="#" class="city-add"><button class="tiny button">Add City</button></a>
  </div>
  <div class="actions">
    <%= f.submit :class => "small button" %>
  </div>
<% end %>
</div>

app/views/trips/_itenerary_list.html.erb
<h1>Listing iteneraries</h1>

<table>
  <tr>
    <th>Item</th>
    <th>Activity to do</th>
    <th>Place to eat</th>
    <th>Place to sleep</th>
    <th>City ID</th>
    <th>Trip ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @iteneraries.each do |itenerary| %>
  <tr>
    <td><%= itenerary.item %></td>
    <td><%= itenerary.activity_to_do %></td>
    <td><%= itenerary.place_to_eat %></td>
    <td><%= itenerary.place_to_sleep %></td>
    <td><%= itenerary.city_id %></td>
    <td><%= itenerary.trip_id %></td>
    <td><%= link_to 'Show', itenerary %></td>
    <td><%= link_to 'Edit', edit_itenerary_path(itenerary) %></td>
    <td><%= link_to 'X', itenerary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Itenerary', new_itenerary_path %>

app/views/trips/_new_city_fields.html.erb
<div class="form-container">
  <%= form_for(@city) do |f| %>
    <% if @city.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

        <ul>
        <% @city.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :country %><br />
      <%= f.text_field :country %>
    </div>
    <div class="field">
      <%= f.label :trip_id %><br />
      <%= f.number_field :trip_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>
<fieldset>
  <%= f.label :name, "City" %>
  <%= f.text_field :name %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove City from Trip" %>
  <%= f.fields_for :cities do |builder| %>
    <%= render 'itenerary_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Activity", f, :iteneraries %>
</fieldset>

app/views/trips/edit.html.erb
<h2 class="title-box">Editing Your Trip</h1>
<div class="row">
  <%= render 'form' %>
</div>
<h6 class="title-box-light">
<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>
</h6>

app/views/trips/index.html.erb
<br />
<div class="row title-box">
    <h1 class="white-text">Trips Created by <%= current_user.first_name %> <%= current_user.last_name %><i class="foundicon-globe right"></i></h1>
    <hr />
</div>

<br />
<div class="row">
    <div class="small-12 large-12 columns light-box">
        <table class="", style="width: 100%">
            <tr class="iten-box">
                <th>Title</th>
                <th>Open</th>
                <th>Like</th>
                <th>Begin on</th>
                <th>End on</th>
                <th>Show</th>
                <th>Edit</th>
                <th>Destroy</th>
            </tr>
            <% @trips.each do |trip| %>
                <tr class="iten-box">
                    <td><h2 class="inline"><i class="foundicon-globe"></i> <%= link_to trip.title, trip %></h2></td>
                    <td><%= trip.open %></td>
                    <td><%= trip.like %></td>
                    <td><%= trip.begin_on %></td>
                    <td><%= trip.end_on %></td>
                    <td><i class="foundicon-website"></i> <%= link_to 'Show', trip %></td>
                    <td><i class="foundicon-edit"></i> <%= link_to 'Edit', edit_trip_path(trip) %></td>
                    <td><i class="foundicon-remove"></i> <%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end %>
        </table>
    </div>
</div>
<br />
<div class="row title-box">
    <h4 style="color: white"><i class="foundicon-plus medium-icon"></i> <%= link_to 'Create New Trip', new_trip_path, :class => "white-link" %></h4>
    <hr />
</div>

app/views/trips/new.html.erb
<div class="row">

<h2 class="title-box">Editing Your Trip</h1>
</h2>
  <%= render 'form' %>
<h6 class="title-box-light">
  <%= link_to 'Back', trips_path %>
</h6>
</div>

app/views/trips/show.html.erb
<div class="row show-container">
  <section id="sidebar" role="complementary">
    <br />
    <div class="small-3 large-3 columns light-box side">
      <div class="iten-box">
        <span class="small-text">
          <%= image_tag current_user.gravatar_url :class => "inline" %>
          <h4 class="inline"><%= current_user.first_name %> <%= current_user.last_name %></h2><br />
          <hr />
          Feeling <%= current_user.mood %><br />
          Currently in <%= current_user.current_location %><br />
          From <%= current_user.home_base %><br />
          Goal: <%= current_user.goal %><br />
          Bio: <%= current_user.bio %><br />
        </span>
      </div>
      <br />
      <br />
      <div>
        <div class="iten-box">
          <div class="title-box">Companions of <%= current_user.first_name %> for <%= @trip.title %></div>
          <ul class="small-text">
          <% current_user.companionships.each do |companionship| %>
            <li>
              <%= link_to companionship.companion.first_name, user_path(companionship.companion) %>
              (<%= link_to "X", companionship, :method => :delete %>)
            </li>
          <% end %>
          <hr />
            <li><%= link_to "Add Companion to", users_path %> <%= @trip.title %></li>

          </ul>
        </div>
        <br />
        <div class="iten-box">
          <div class="title-box">Friends of <%= current_user.first_name %></div>
          <ul class="small-text">
          <% current_user.friendships.each do |friendship| %>
            <li>
              <%= link_to friendship.friend.first_name, user_path(friendship.friend) %>
              (<%= link_to "X", friendship, :method => :delete %>)
            </li>
          <% end %>
          <hr />
          <li><%= link_to "Find New Friends", users_path %></li>

          </ul>
        </div>

      </div>
    </div>
  </section>
  <section role="main">
  <div class="small-9 large-9 columns">
    <div class="row">


      <div class="small-12 large-12 columns">
        <p id="notice title-box-light"><%= notice %></p>
        <h3 class="comp-title-box">
          <i class="foundicon-globe left"></i>
          <%= @trip.title %>
          <% if @trip.open %>
            •<span>This trip is open to other travelers.</span>
          <% end %>
          <%= link_to 'Edit', edit_trip_path(@trip), :class => "right link" %>
        </h3>
        <div class="">
          <ul class="tags left">
            <% @trip.tag_list.each do |t| %>
              <li class="tag"><%= link_to t, tag_path(t) %></li>
            <% end %>
          </ul>
          <br />
        </div>
        <br />
        <section class="light-box">
        <ul>
          <% @trip.cities.each do |i| %>
            <li class="small-text">
              <div>
                <span class ="right"><%= link_to "×", city_path(i), :method => :delete, :remote => true, :confirm => "Are you sure you want to remove this city? If item is deleted, reload the page for the change to be shown" %></span>
                <h2 class="title-box-light white-text"><i class="foundicon-flag left"></i> <%= i.name %></h2>
                <h4 class="inline"><%= i.country %></h4>
                •created: <%= i.created_at.strftime("%B %-d, %Y %-l:%M %p") %>
                •updated: <%= i.updated_at.strftime("%B %-d, %Y %-l:%M %p") %>
              </div>
              <strong>Itenerary for <%= i.name %></strong>
              <ul class="">
                <% i.iteneraries.each do |n| %>
                <section class="title-box-light">
                  <span class ="right"><%= link_to "×", itenerary_path(n), :method => :delete, :remote => true, :confirm => "Are you sure you want to remove this itenerary? If item is deleted, reload the page for the change to be shown" %></span>
                  <li><%= n.item %></li>
                  <li class="list-inline">•<%= "This is a thing to do" if n.activity_to_do %></li>
                  <li class="list-inline">•<%= "This is a place to eat" if n.place_to_eat %></li>
                  <li class="list-inline">•<%= "This is a place to sleep" if n.place_to_sleep %></li>
                  <li class="list-inline">•<%= n.created_at.strftime("%B %-d, %Y %-l:%M %p") %></li>
                  <li class="list-inline">•<%= n.updated_at.strftime("%B %-d, %Y %-l:%M %p") %></li>
                </section>
                <% end %>
              </ul>
            </li>
            <hr />
        <% end %>
        </ul>
        </section>
        <hr />
        <h5 class="title-box-light">•<%= link_to 'Edit This Trip', edit_trip_path(@trip) %></h5>
        <div class="light-box">
          <%= render :partial => 'comments/comments', :collection => @comments, :as => :comment %>
          <br />
          <%= render :partial => 'comments/form', :locals => { :comment => @new_comment } %>
        </div>
      </div>
    </div>
  </div>
</div>
</section>
<br />
<div class="row">
  <div class="small-3 large-3 columns">
  </div>
  <div class="small-1 large-1 columns">
  </div>
  <div class="small-8 large-8 columns">


  </div>

</div>

app/views/trips/show_old.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h2>
    <%= @trip.title %>
  </h2>

  <p>
    <b>Like:</b>
    <%= @trip.like %>
  </p>

  <p>
    <span><b>Begin on: </b> <%= @trip.begin_on %></span>
  </p>

  <p>
    <span><b>End on: </b> <%= @trip.end_on %></span>
  </p>
  <p>
    <% @cities_in_current_trip.each do |i| %>
    <%= i.name %><br />
    <%= i.country %><br />
    <%= i.created_at.strftime("%B %-d, %Y %-l:%M %p") %><br />
    <%= i.updated_at.strftime("%B %-d, %Y %-l:%M %p") %><br />

  <% end %>
  <hr />
  <% @iteneraries_of_current_trip.each do |i| %>
    <%= i.item %> <br />
    <%= "This is a thing to do" if i.activity_to_do %> <br />
    <%= "This is a place to eat" if i.place_to_eat %> <br />
    <%= "This is a place to sleep" if i.place_to_sleep %> <br />
    <%= i.created_at.strftime("%B %-d, %Y %-l:%M %p") %> <br />
    <%= i.updated_at.strftime("%B %-d, %Y %-l:%M %p") %> <br />

  <% end %>
  <hr />
  <%= link_to 'Edit', edit_trip_path(@trip) %> |
  <%= link_to 'Back', trips_path %>
  <p>
    <hr />
    <%= @cities_in_current_trip.inspect %><br />
    <hr />
    <%= @iteneraries_of_current_trip.inspect %><br />
    <hr />
    hi<%= @array_of_items %><br />
  </p>

</div>