config/routes.rb
TravelApp::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to => "welcome#index"

  resources :companionships
  resources :friendships
  resources :favorites
  resources :iteneraries
  resources :cities
  resources :trips
  resources :users

  resources :comments, :only => [:create, :destroy]

  get 'tags/:tag', to: 'trips#index', as: :tag

end

app/models/companionship.rb
class Companionship < ActiveRecord::Base
  attr_accessible :companion_id, :user_id
  belongs_to :user
  belongs_to :companion, :class_name => "User"
end

app/controllers/companionships_controller.rb
class CompanionshipsController < ApplicationController
  def create
    @companionship = current_user.companionships.build(:companion_id => params[:companion_id])
    if @companionship.save
      flash[:notice] = "Added companion."
      redirect_to root_url
    else
      flash[:error] = "Unable to add companion."
      redirect_to current_user
    end
  end

  def destroy
    @companionship = current_user.companionships.find(params[:id])
    @companionship.destroy
    flash[:notice] = "Removed companion."
    redirect_to current_user
  end
end

app/helpers/companionships_helper.rb
module CompanionshipsHelper
end

app/views/companionships/_form.html.erb
<%= form_for(@companionship) do |f| %>
  <% if @companionship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@companionship.errors.count, "error") %> prohibited this companionship from being saved:</h2>

      <ul>
      <% @companionship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :companion_id %><br />
    <%= f.number_field :companion_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companionships/edit.html.erb
<h1>Editing companionship</h1>

<%= render 'form' %>

<%= link_to 'Show', @companionship %> |
<%= link_to 'Back', companionships_path %>

app/views/companionships/index.html.erb
<h1>Listing companionships</h1>

<table>
  <tr>
    <th>User</th>
    <th>Companion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companionships.each do |companionship| %>
  <tr>
    <td><%= companionship.user_id %></td>
    <td><%= companionship.companion_id %></td>
    <td><%= link_to 'Show', companionship %></td>
    <td><%= link_to 'Edit', edit_companionship_path(companionship) %></td>
    <td><%= link_to 'Destroy', companionship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Companionship', new_companionship_path %>

app/views/companionships/new.html.erb
<h1>New companionship</h1>

<%= render 'form' %>

<%= link_to 'Back', companionships_path %>

app/views/companionships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @companionship.user_id %>
</p>

<p>
  <b>Companion:</b>
  <%= @companionship.companion_id %>
</p>


<%= link_to 'Edit', edit_companionship_path(@companionship) %> |
<%= link_to 'Back', companionships_path %>