config/routes.rb
TravelApp::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to => "welcome#index"

  resources :companionships
  resources :friendships
  resources :favorites
  resources :iteneraries
  resources :cities
  resources :trips
  resources :users

  resources :comments, :only => [:create, :destroy]

  get 'tags/:tag', to: 'trips#index', as: :tag

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :bio, :current_location, :first_name, :goal, :home_base, :last_name, :mood
  has_many :trips, inverse_of: :user

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :companionships
  has_many :companions, :through => :companionships
  has_many :inverse_companionships, :class_name => "Companionship", :foreign_key => "companion_id"
  has_many :inverse_companions, :through => :inverse_companionships, :source => :user

  include Gravtastic
  gravtastic

  acts_as_tagger
  acts_as_taggable

  validates :email, :presence => true
  validates :email, :uniqueness => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="iten-box">

  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :mood %><br />
      <%= f.text_field :mood %>
    </div>
    <div class="field">
      <%= f.label :home_base %><br />
      <%= f.text_field :home_base %>
    </div>
    <div class="field">
      <%= f.label :current_location %><br />
      <%= f.text_field :current_location %>
    </div>
    <div class="field">
      <%= f.label :bio %><br />
      <%= f.text_field :bio %>
    </div>
    <div class="field">
      <%= f.label :goal %><br />
      <%= f.text_field :goal %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<br />
<div class="title-box row">
    <h1 class="white-text">Users Hub <i class="foundicon-people right"></i></h1>
    <hr />
</div>

<br />

<div class="row">
    <% @users.each do |user| %>
        <div class="small-6 large-6 columns light-box">
            <div class="row small-text">
                <div class="small-4 large-4 columns">
                    <% if user.gravatar_url %>
                        <%= link_to image_tag(user.gravatar_url(:size => "150")), user, :class => "inline" %>
                    <% else %>
                        <img src="http://si0.twimg.com/profile_images/2236267469/image.jpg" style="width: 80px">
                    <% end %>
                </div>
                <div class="small-8 large-8 columns dark-box">
                    <h5 class="comp-title-box"><%= link_to "#{user.first_name} #{user.last_name}", user, :class => "link" %><span class="right"><%= user.mood %> <i class="foundicon-smiley"></i></span></h5>
                    <div class="profile-box"><i class="foundicon-location"></i> <%= user.current_location %></div>
                    <div class="profile-box"><i class="foundicon-star"></i> <%= user.goal %></div>
                    <% if current_user.friendships.size > 0  && user.id != current_user.id %>
                        <% current_user.friendships.each do |i| %>
                            <% if i.friend_id == user.id && user.id != current_user.id%>
                                <div class="profile-box">
                                    <%= link_to "", i, :method => :delete, :class => "foundicon-minus link" %>
                                    <%= link_to "Friend", friendships_path(:friend_id => user), :method => :post, :class => "link" %>
                                </div>
                            <% end %>
                        <% end %>
                    <% elsif user.id == current_user.id %>
                        <span class="blank"></span>
                    <% end %>
                    <span>
                        <div class="profile-box">
                            <%= link_to "", friendships_path(:friend_id => user), :method => :post, :class => "foundicon-plus link" %>
                            <%= link_to "Friend", friendships_path(:friend_id => user), :method => :post, :class => "link" %>
                        </div>
                    </span>
                    <% if current_user.companionships.size > 0  && user.id != current_user.id && %>
                        <% current_user.companionships.each do |i| %>
                            <% if i.companion_id == user.id %>
                                <div class="profile-box">
                                    <%= link_to "", i, :method => :delete, :class => "foundicon-minus link" %>
                                    <%= link_to "Companion", companionships_path(:companion_id => user), :method => :post, :class => "link" %>
                                </div>
                            <% end %>
                        <% end %>
                    <% elsif user.id == current_user.id %>
                        <span class="blank"></span>
                    <% end %>
                    <span>
                        <div class="profile-box">
                            <%= link_to "", companionships_path(:companion_id => user), :method => :post, :class => "foundicon-plus link" %>
                            <%= link_to "Companion", companionships_path(:companion_id => user), :method => :post, :class => "link" %>
                        </div>
                    </span>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<br />
<br />
<div class="row light-box-sign-up">
<p id="notice"><%= notice %></p>

<p><%= image_tag current_user.gravatar_url :class => "" %>
</p>
<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Mood:</b>
  <%= @user.mood %>
</p>

<p>
  <b>Home base:</b>
  <%= @user.home_base %>
</p>

<p>
  <b>Current location:</b>
  <%= @user.current_location %>
</p>

<p>
  <b>Bio:</b>
  <%= @user.bio %>
</p>

<p>
  <b>Goal:</b>
  <%= @user.goal %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>